# Generated by Django 3.0.4 on 2020-03-25 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgApp', '0003_downloadimagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadimagemodel',
            old_name='name',
            new_name='name_To_Download',
        ),
    ]
