# Generated by Django 3.0.4 on 2020-03-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgApp', '0004_auto_20200325_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadimagemodel',
            name='ext',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
