# Generated by Django 3.0.4 on 2020-03-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgApp', '0005_downloadimagemodel_ext'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='ext',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
